/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './App.{js,jsx,ts,tsx}',
        './src/**/*.{js,jsx,ts,tsx}',
        '../../packages/ui/src/**/*.{js,jsx,ts,tsx}',
    ],
    darkMode: 'class',
    presets: [require('nativewind/preset')],
    theme: {
        extend: {
            colors: {
                // Semantic roles mirror the mobile tokens and map cleanly to web/MUI:
                // background.default, background.paper, text.primary, text.secondary,
                // primary.main, secondary.main, divider, and error.main.
                background: '#f8fafc',
                'background-dark': '#161719',
                surface: '#ffffff',
                'surface-dark': '#202023',
                'surface-variant': '#f1f5f9',
                'surface-variant-dark': '#313335',
                primary: '#d79a00',
                'primary-container': '#ffedb3',
                'primary-container-dark': '#6b4d00',
                'on-primary': '#0f172a',
                'on-primary-dark': '#191c21',
                'on-primary-container': '#5c4300',
                'on-primary-container-dark': '#ffedb3',
                secondary: '#5897d6',
                'secondary-container': '#dbeafe',
                'secondary-container-dark': '#21466e',
                'on-secondary': '#0f172a',
                'on-secondary-dark': '#191c21',
                'on-secondary-container': '#1e3a5f',
                'on-secondary-container-dark': '#dbeafe',
                'on-surface': '#0f172a',
                'on-surface-dark': '#f8fafc',
                'on-surface-variant': '#64748b',
                'on-surface-variant-dark': '#94a3b8',
                outline: '#cbd5e1',
                'outline-dark': '#475569',
                'outline-variant': '#e2e8f0',
                'outline-variant-dark': '#334155',
                error: '#dc2626',
                'error-dark': '#fca5a5',
                'error-container': '#fee2e2',
                'error-container-dark': '#7f1d1d',
                'on-error-container': '#7f1d1d',
                'on-error-container-dark': '#fee2e2',
                scrim: '#00000080',
            },
        },
    },
    plugins: [],
};
